# Generated by Django 5.1.7 on 2025-03-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Gifts'},
        ),
    ]
