# Generated by Django 5.1.7 on 2025-04-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_wish_delete_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
