"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.
Buggered about with by me!

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=BASE_DIR / ".env")


def require_env(key):
    value = os.getenv(key)
    if value is None:
        raise ValueError(f"Missing required environment variable: {key}")
    return value


ENVIRONMENT = require_env("ENVIRONMENT")
DATABASE_NAME = require_env("DATABASE_NAME")

# NOTE: These print statements will appear twice in the console during development
# due to Django's autoreloader importing settings.py more than once.
# This is expected and harmless. Proper logging will replace this later.
if ENVIRONMENT == "dev":
    print(f"Starting with environment: {ENVIRONMENT}")
    print(f"Starting with database name: {DATABASE_NAME}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = require_env("DJANGO_SECRET_KEY")

# Environment-specific settings
if ENVIRONMENT == "dev":
    DEBUG = True
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "192.168.68.102"]
elif ENVIRONMENT == "qa":
    DEBUG = False
    ALLOWED_HOSTS = ["giftsqa.pythonanywhere.com"]
else:  # prod
    DEBUG = False
    ALLOWED_HOSTS = ["gifts.richcairns.com"]

if ENVIRONMENT in ["qa", "prod"]:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 3600  # Increase to 31536000 for prod later
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    "gifts",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "widget_tweaks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "gifts.context_processors.custom_context_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / DATABASE_NAME,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

# If USE-TZ = True, Django uses UTC under the hood - this setting just affects what's displayed.
TIME_ZONE = "Europe/London"

USE_TZ = True  # (this should stay True unless you have a strong reason)

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
if ENVIRONMENT in ["qa", "prod"]:
    STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "my_wishes"
LOGOUT_REDIRECT_URL = "login"

# Email settings
if ENVIRONMENT == "dev":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.mailgun.org"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = require_env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = require_env("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = require_env("DEFAULT_FROM_EMAIL")
